"""initial schema

Revision ID: 0ed68edeb7c3
Revises: 
Create Date: 2026-09-18 19:49:16.885998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed68edeb7c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operational_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='operationstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='operationpriority'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_data_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operational_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_data_snapshots_operation_id'), 'external_data_snapshots', ['operation_id'], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('contributing_factors', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operational_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_operation_id'), 'risk_events', ['operation_id'], unique=False)
    op.create_table('intervention_outcomes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('risk_event_id', sa.String(length=36), nullable=False),
    sa.Column('predicted_outcome', sa.Text(), nullable=False),
    sa.Column('operator_action', sa.Text(), nullable=True),
    sa.Column('actual_outcome', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['risk_event_id'], ['risk_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intervention_outcomes_risk_event_id'), 'intervention_outcomes', ['risk_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intervention_outcomes_risk_event_id'), table_name='intervention_outcomes')
    op.drop_table('intervention_outcomes')
    op.drop_index(op.f('ix_risk_events_operation_id'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_external_data_snapshots_operation_id'), table_name='external_data_snapshots')
    op.drop_table('external_data_snapshots')
    op.drop_table('operational_records')
    # ### end Alembic commands ###
